import { _electron as electron, expect } from '@playwright/test';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
const root = resolve('.'), data = await mkdtemp(join(tmpdir(), 'settings-desktop-'));
await mkdir(join(data, 'updates')); await writeFile(join(data, 'updates/settings.json'), JSON.stringify({ repository: 'fixture/public', automatic: false }));
await mkdir(join(data, 'drivers')); await writeFile(join(data, 'drivers/settings.json'), JSON.stringify({ automatic: false, installed: {}, selected: {} }));
await mkdir('test-artifacts', { recursive: true });
const app = await electron.launch({ executablePath: process.env.LOCAL_DB_VIEWER_EXECUTABLE, args: process.env.LOCAL_DB_VIEWER_EXECUTABLE ? [] : [root], env: { ...process.env, LOCAL_DB_VIEWER_DATA_DIR: data } });
try {
  const page = await app.firstWindow(), errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('button', { name: 'Подключить базу', exact: true }).click();
  await page.getByRole('tab', { name: 'SSH/SSL', exact: true }).click();
  await page.getByLabel('Use SSH tunnel', { exact: true }).check();
  await page.getByLabel('SSH host', { exact: true }).fill('bastion.example');
  await page.getByLabel('SSH authentication', { exact: true }).selectOption('password');
  await page.getByLabel('SSH password', { exact: true }).fill('fixture-private');
  await page.getByLabel('Use truststore', { exact: true }).selectOption('file');
  await expect(page.getByLabel('Truststore / CA file', { exact: true })).toBeVisible();
  await page.getByLabel('Client certificate', { exact: true }).selectOption('store');
  await expect(page.getByLabel('Client keystore file', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-artifacts/connection-ssh-ssl.png' });
  await page.getByRole('tab', { name: 'General', exact: true }).click();
  await page.getByLabel('СУБД', { exact: true }).selectOption('sqlite');
  await page.getByLabel('Название', { exact: true }).fill('Scoped database');
  const database = join(data, 'scoped.sqlite');
  await app.evaluate((_electron, path) => { const { DatabaseSync } = process.getBuiltinModule('node:sqlite'); const db = new DatabaseSync(path); db.exec('CREATE TABLE visible_table(id INTEGER); CREATE TABLE excluded_table(id INTEGER); INSERT INTO visible_table VALUES(7); CREATE VIEW visible_view AS SELECT id FROM visible_table; CREATE TRIGGER visible_trigger AFTER INSERT ON visible_table BEGIN SELECT 1; END'); db.close(); }, database);
  await page.locator('.endpoint-field input').fill(database);
  await page.getByRole('tab', { name: 'Options', exact: true }).click();
  await page.getByLabel('Switch schema', { exact: true }).selectOption('manual');
  await page.getByLabel('Load sources for', { exact: true }).selectOption('none');
  await page.getByLabel('SQL keyword case', { exact: true }).selectOption('lower');
  await page.getByLabel('Indent size', { exact: true }).fill('2');
  await page.getByLabel('Single session mode', { exact: true }).check();
  await page.getByLabel('Keep-alive interval, sec', { exact: true }).fill('60');
  await page.getByLabel('Auto-disconnect after, sec', { exact: true }).fill('300');
  await page.getByRole('tab', { name: 'Schemas', exact: true }).click();
  await page.getByRole('button', { name: 'Загрузить каталоги', exact: true }).click();
  await page.getByRole('button', { name: 'main · загрузить schemas', exact: true }).click();
  await page.getByLabel('Introspection scope', { exact: true }).selectOption('selected');
  await page.getByRole('checkbox', { name: 'main', exact: true }).check();
  await page.getByLabel('Object exclude patterns', { exact: true }).fill('*.excluded_table');
  await page.screenshot({ path: 'test-artifacts/connection-schemas.png' });
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.locator('dialog')).toHaveCount(0);
  const result = await page.evaluate(async () => {
    const [profile] = await window.studio.profiles.list();
    const tables = await window.studio.metadata({ profileId: profile.id, kind: 'tables', catalog: 'main', schema: 'main' });
    const schema = await window.studio.schema.load({ profileId: profile.id, catalog: 'main', schema: 'main' });
    return { profile, tables, schema };
  });
  expect(result.profile.jdbc.options.singleSession).toBe(true); expect(result.profile.jdbc.options.keepAliveSeconds).toBe(60);
  expect(result.tables.rows.map(row => row[0])).toContain('visible_table'); expect(result.tables.rows.map(row => row[0])).not.toContain('excluded_table');
  expect(result.schema.tables.map(table => table.name)).toContain('visible_table'); expect(result.schema.tables.map(table => table.name)).not.toContain('excluded_table');
  expect(result.profile.jdbc.options.switchSchema).toBe('manual');
  expect(result.profile.jdbc.options.loadSources).toBe('none');
  expect(result.profile.jdbc.options.codeStyle).toEqual({ keywordCase: 'lower', indentSize: 2, useTabs: false });
  const automatic = await page.evaluate(profileId => window.studio.sources.load({ profileId, catalog:'main', schema:'main', automatic:true }), result.profile.id);
  expect(automatic.skipped).toBe(true); expect(automatic.objects).toEqual([]);
  await page.getByRole('button', { name: 'Исходники объектов', exact:true }).click();
  await page.getByRole('button', { name:'visible_view view', exact:true }).click();
  await expect(page.getByLabel('SQL исходника')).toHaveValue('CREATE VIEW visible_view AS SELECT id FROM visible_table');
  await page.getByRole('button', { name:'visible_trigger trigger', exact:true }).click();
  expect(await page.getByLabel('SQL исходника').inputValue()).toContain('CREATE TRIGGER');
  await page.screenshot({ path:'test-artifacts/object-sources.png' });
  await page.getByRole('button', { name:'visible_view view', exact:true }).click();
  await page.getByRole('button', { name:'Открыть в SQL-консоли', exact:true }).click();
  await expect(page.getByRole('tab', { name:'visible_view.sql', exact:true })).toBeVisible();
  const original = "SELECT id, 'UPPER;select' AS [Value] FROM visible_table WHERE id=7";
  await page.locator('.monaco-editor').click({ position: {x:100,y:20} });
  const modifier=process.platform==='darwin'?'Meta':'Control';
  await page.keyboard.press(`${modifier}+a`); await page.keyboard.insertText(original); await page.keyboard.press('Escape');
  await page.getByRole('button', { name:'Форматировать SQL', exact:true }).click();
  const currentSQL=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('studio.tabs')).find(tab=>tab.name==='visible_view.sql')?.sql?.replace(/\r\n/g,'\n'));
  await expect.poll(currentSQL).toContain('select\n  id,');
  expect(await currentSQL()).toContain("'UPPER;select'"); expect(await currentSQL()).toContain('[Value]');
  await page.keyboard.press(`${modifier}+z`); await expect.poll(currentSQL).toBe(original);
  await page.keyboard.press(`${modifier}+Shift+l`);
  await expect.poll(currentSQL).toContain('select\n  id,');
  await page.getByRole('button', { name:'Выполнить' }).click();
  await expect(page.locator('.result-state')).toHaveText('FINISHED',{timeout:30000});
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody tr')).toContainText('UPPER;select');
  await page.getByRole('button', { name:'Отключить сессию', exact:true }).click();
  await page.getByRole('button', { name:'Исходники объектов', exact:true }).click();
  await app.evaluate((_electron,path)=>{ const {DatabaseSync}=process.getBuiltinModule('node:sqlite'); const db=new DatabaseSync(path); db.exec('CREATE VIEW second_view AS SELECT 2'); db.close(); },database);
  await expect(page.getByRole('button', {name:'second_view view',exact:true})).toHaveCount(0);
  await page.getByRole('button', {name:'Обновить исходники',exact:true}).click();
  await expect(page.getByRole('button', {name:'second_view view',exact:true})).toBeVisible({timeout:30000});
  await page.getByRole('button', {name:'Закрыть исходники',exact:true}).click();
  await page.reload();
  await expect(page.getByRole('tab', {name:'visible_view.sql',exact:true})).toBeVisible();
  expect((await page.evaluate(()=>window.studio.profiles.list()))[0].jdbc.options.codeStyle.indentSize).toBe(2);
  expect(errors).toEqual([]);
  await writeFile('test-artifacts/settings-desktop-results.json',JSON.stringify({passed:true,platform:process.platform,checks:['options-persistence','source-mode-none','source-read','source-refresh','dialect-formatting','format-undo','formatted-SQL-execution']},null,2));
  console.log('PASS: source loading policy, real SQLite views/triggers, refresh, SQL code style, undo and execution');
  console.log('PASS: SSH/certificate controls, draft schema discovery, persisted Options, Explorer and completion scope filters');
} catch(error) { const page=await app.firstWindow(); await page.screenshot({path:'test-artifacts/settings-failure.png'}).catch(()=>{}); console.error(await page.locator('dialog').innerText({timeout:1000}).catch(()=>'')); throw error; } finally { await app.close(); }
