import { _electron as electron, expect } from '@playwright/test';
import { mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
const root = resolve('.'), data = await mkdtemp(join(tmpdir(), 'settings-desktop-'));
await mkdir(join(data, 'updates')); await writeFile(join(data, 'updates/settings.json'), JSON.stringify({ repository: 'fixture/public', automatic: false }));
await mkdir(join(data, 'drivers')); await writeFile(join(data, 'drivers/settings.json'), JSON.stringify({ automatic: false, installed: {}, selected: {} }));
await mkdir('test-artifacts', { recursive: true });
const app = await electron.launch({ executablePath: process.env.LOCAL_DB_VIEWER_EXECUTABLE, args: process.env.LOCAL_DB_VIEWER_EXECUTABLE ? [] : [root], env: { ...process.env, LOCAL_DB_VIEWER_DATA_DIR: data } });
try {
  const page = await app.firstWindow(), errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('button', { name: 'Подключить базу', exact: true }).click();
  await page.getByRole('tab', { name: 'SSH/SSL', exact: true }).click();
  await page.getByLabel('Use SSH tunnel', { exact: true }).check();
  await page.getByLabel('SSH host', { exact: true }).fill('bastion.example');
  await page.getByLabel('SSH authentication', { exact: true }).selectOption('password');
  await page.getByLabel('SSH password', { exact: true }).fill('fixture-private');
  await page.getByLabel('Use truststore', { exact: true }).selectOption('file');
  await expect(page.getByLabel('Truststore / CA file', { exact: true })).toBeVisible();
  await page.getByLabel('Client certificate', { exact: true }).selectOption('store');
  await expect(page.getByLabel('Client keystore file', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-artifacts/connection-ssh-ssl.png' });
  await page.getByRole('tab', { name: 'General', exact: true }).click();
  await page.getByLabel('СУБД', { exact: true }).selectOption('sqlite');
  await page.getByLabel('Название', { exact: true }).fill('Scoped database');
  const database = join(data, 'scoped.sqlite');
  await app.evaluate((_electron, path) => { const { DatabaseSync } = process.getBuiltinModule('node:sqlite'); const db = new DatabaseSync(path); db.exec('CREATE TABLE visible_table(id INTEGER); CREATE TABLE excluded_table(id INTEGER)'); db.close(); }, database);
  await page.locator('.endpoint-field input').fill(database);
  await page.getByRole('tab', { name: 'Options', exact: true }).click();
  await page.getByLabel('Single session mode', { exact: true }).check();
  await page.getByLabel('Keep-alive interval, sec', { exact: true }).fill('60');
  await page.getByLabel('Auto-disconnect after, sec', { exact: true }).fill('300');
  await page.getByRole('tab', { name: 'Schemas', exact: true }).click();
  await page.getByRole('button', { name: 'Загрузить каталоги', exact: true }).click();
  await page.getByRole('button', { name: 'main · загрузить schemas', exact: true }).click();
  await page.getByLabel('Introspection scope', { exact: true }).selectOption('selected');
  await page.getByRole('checkbox', { name: 'main', exact: true }).check();
  await page.getByLabel('Object exclude patterns', { exact: true }).fill('*.excluded_table');
  await page.screenshot({ path: 'test-artifacts/connection-schemas.png' });
  await page.getByRole('button', { name: 'Сохранить', exact: true }).click();
  await expect(page.locator('dialog')).toHaveCount(0);
  const result = await page.evaluate(async () => {
    const [profile] = await window.studio.profiles.list();
    const tables = await window.studio.metadata({ profileId: profile.id, kind: 'tables', catalog: 'main', schema: 'main' });
    const schema = await window.studio.schema.load({ profileId: profile.id, catalog: 'main', schema: 'main' });
    return { profile, tables, schema };
  });
  expect(result.profile.jdbc.options.singleSession).toBe(true); expect(result.profile.jdbc.options.keepAliveSeconds).toBe(60);
  expect(result.tables.rows.map(row => row[0])).toContain('visible_table'); expect(result.tables.rows.map(row => row[0])).not.toContain('excluded_table');
  expect(result.schema.tables.map(table => table.name)).toContain('visible_table'); expect(result.schema.tables.map(table => table.name)).not.toContain('excluded_table');
  expect(errors).toEqual([]);
  console.log('PASS: SSH/certificate controls, draft schema discovery, persisted Options, Explorer and completion scope filters');
} finally { await app.close(); }
