import type { JdbcSettings } from './jdbc';
import type { DatabaseEngine } from './shared';
import { tokenize } from './sql-lexer';

export type CodeStyle = NonNullable<NonNullable<JdbcSettings['options']>['codeStyle']>;
export const defaultCodeStyle: CodeStyle = { keywordCase: 'upper', indentSize: 4, useTabs: false };

/** Applies casing only to SQL generated by the IDE. Quoted names stay byte-for-byte intact. */
export function generatedStyle(sql: string, engine: DatabaseEngine, style = defaultCodeStyle): string {
  if (style.keywordCase === 'preserve') return sql;
  const words = new Set('SELECT FROM WHERE ORDER BY GROUP HAVING LIMIT OFFSET FETCH FIRST NEXT ROWS ONLY JOIN LEFT RIGHT FULL INNER OUTER ON AND AS COUNT SUM AVG DISTINCT IS NOT NULL'.split(' '));
  const tokens = tokenize(sql, engine, 10000).tokens;
  let result = '', end = 0;
  for (const token of tokens) {
    if (token.kind !== 'name' || token.quoted || !words.has(token.value.toUpperCase())) continue;
    result += sql.slice(end, token.start) + (style.keywordCase === 'upper' ? token.text.toUpperCase() : token.text.toLowerCase());
    end = token.end;
  }
  return result + sql.slice(end);
}
