import { useEffect, useRef, useState } from 'react';
import { X, FolderOpen, RefreshCw } from 'lucide-react';
import type { Profile } from './shared';
import type { DdlFile, DdlMapping, DdlPreview } from './ddl';

export function DdlDialog({ profiles, profile, onClose, onOpen }: { profiles: Profile[]; profile?: Profile; onClose(): void; onOpen(mapping: DdlMapping, sql: string, name: string): void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [mappings, setMappings] = useState<DdlMapping[]>([]), [draft, setDraft] = useState<DdlMapping>();
  const [files, setFiles] = useState<DdlFile[]>([]), [selected, setSelected] = useState(''), [sql, setSQL] = useState('');
  const [preview, setPreview] = useState<DdlPreview>(), [checked, setChecked] = useState<string[]>([]);
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
  const file = files.find(item => item.file === selected), dirty = !!file && sql !== file.sql;
  const saved = draft && mappings.some(item => JSON.stringify(item) === JSON.stringify(draft));
  async function act(work: () => Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await work(); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  useEffect(() => { dialog.current?.showModal(); void act(async () => setMappings(await window.studio.ddl.list())); }, []);
  const reset = () => { setFiles([]); setSelected(''); setSQL(''); setPreview(undefined); setChecked([]); };
  const change = (value: Partial<DdlMapping>) => { if (draft) setDraft({ ...draft, ...value }); reset(); };
  async function readFiles(id: string) { const values = await window.studio.ddl.files(id); setFiles(values); const next = values.find(item => item.file === selected) ?? values[0]; setSelected(next?.file ?? ''); setSQL(next?.sql ?? ''); }
  return <dialog ref={dialog} className="ddl-dialog connection-dialog" onCancel={event => { if (busy || dirty) { event.preventDefault(); setError('Сохраните SQL или отмените правки перед закрытием.'); } else onClose(); }}>
    <div className="dialog-heading"><FolderOpen size={22} /><div><h2>DDL mappings</h2><p>Связь схемы с локальным каталогом SQL</p></div><button type="button" className="icon-button close-dialog" aria-label="Закрыть DDL mappings" disabled={busy || dirty} onClick={onClose}><X size={18} /></button></div>
    <div className="dialog-body"><fieldset disabled={busy} className="ddl-controls">
      <div className="form-row"><label>Mapping<select aria-label="DDL mapping" disabled={dirty} value={draft?.id ?? ''} onChange={event => { const next = mappings.find(item => item.id === event.target.value); setDraft(next); reset(); if (next) void act(() => readFiles(next.id)); }}><option value="">Выберите mapping</option>{mappings.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="button" className="button secondary" disabled={dirty || !profiles.length} onClick={() => { const source = profile ?? profiles[0]; if (!source) return; reset(); setDraft({ id: crypto.randomUUID(), name: `${source.name} DDL`, profileId: source.id, directory: '', catalog: source.catalog, schema: source.schema }); }}>Новый mapping</button></div>
      {draft && <>
        <fieldset disabled={dirty} className="ddl-controls"><div className="form-row"><label>Имя mapping<input aria-label="Имя mapping" value={draft.name} onChange={event => change({ name: event.target.value })} /></label><label>Data source<select aria-label="DDL data source" value={draft.profileId} onChange={event => { const source = profiles.find(item => item.id === event.target.value); if (source) change({ profileId: source.id, catalog: source.catalog, schema: source.schema }); }}>{profiles.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>
        <label>Каталог SQL<div className="endpoint-field"><input aria-label="Каталог DDL" value={draft.directory} onChange={event => change({ directory: event.target.value })} /><button type="button" className="button secondary" onClick={() => void act(async () => { const directory = await window.studio.ddl.chooseDirectory(); if (directory) change({ directory }); })}>Выбрать каталог</button></div></label>
        <div className="form-row"><label>Catalog / database<input aria-label="DDL catalog" value={draft.catalog} onChange={event => change({ catalog: event.target.value })} /></label><label>Schema<input aria-label="DDL schema" value={draft.schema} onChange={event => change({ schema: event.target.value })} /></label></div>
        <div className="ddl-actions"><button type="button" className="button primary" onClick={() => void act(async () => { const value = await window.studio.ddl.save(draft); setDraft(value); setMappings(await window.studio.ddl.list()); await readFiles(value.id); setMessage('Mapping сохранён.'); })}>Сохранить mapping</button><button type="button" className="button secondary" disabled={!saved} onClick={() => void act(async () => { await readFiles(draft.id); setPreview(undefined); })}><RefreshCw size={14} />Перечитать файлы</button><button type="button" className="button secondary" disabled={!saved} onClick={() => void act(async () => { const result = await window.studio.ddl.preview(draft.id); setPreview(result); setChecked(result.differences.filter(item => item.status === 'new').map(item => item.file)); })}>Сравнить с БД</button><button type="button" className="button secondary" disabled={!saved} onClick={() => onOpen(draft, '-- Локальные подсказки из DDL mapping\n-- Выполнение SQL использует выбранное подключение\n\nSELECT ', 'ddl-console.sql')}>Консоль с DDL-подсказками</button></div>
        <small>Серверная выгрузка: Trino/Presto, PostgreSQL 14–18, MySQL/MariaDB, SQL Server 2019–2022, ClickHouse, SQLite. PostgreSQL / SQL Server: обычные таблицы, constraints, indexes и views; неподдерживаемые свойства останавливают выгрузку. Каждый mapping — один catalog/schema. Это определения объектов, не backup базы; SQL применяется из консоли вручную.</small></fieldset>
        {preview && <section className="ddl-preview"><h3>БД → локальные файлы</h3>{preview.warnings.map(warning => <p className="muted" key={warning}>{warning}</p>)}<p className="muted">Выберите файлы для сохранения. Существующие версии попадут в .local-db-viewer-backup. Файлы только на диске сохраняются.</p>{preview.differences.map(item => <details key={item.file}><summary><label className="checkbox-row" onClick={event => event.stopPropagation()}><input type="checkbox" aria-label={`Сохранить ${item.file}`} disabled={item.status === 'same' || item.status === 'local-only'} checked={checked.includes(item.file)} onChange={event => setChecked(values => event.target.checked ? [...values,item.file] : values.filter(value => value !== item.file))} />{item.file}</label><span>SQL ▾ · {({same:'Без изменений',new:'Новый',changed:'Изменён', 'local-only':'Только на диске'})[item.status]}</span></summary><div className="ddl-diff"><div><h4>Локальный SQL</h4><pre>{item.local ?? 'Файл отсутствует'}</pre></div><div><h4>DDL сервера</h4><pre>{item.remote ?? 'Нет в выгрузке'}</pre></div></div></details>)}<button type="button" className="button primary" disabled={!checked.length || dirty} onClick={() => void act(async () => { await window.studio.ddl.writePreview(preview.token, checked); setPreview(undefined); await readFiles(draft.id); setMessage('Выбранные файлы сохранены.'); })}>Сохранить выбранные файлы ({checked.length})</button></section>}
        {!!files.length && <section className="ddl-file-editor"><h3>SQL-файлы</h3><select aria-label="DDL файл" disabled={dirty} value={selected} onChange={event => { setSelected(event.target.value); setSQL(files.find(item => item.file === event.target.value)?.sql ?? ''); }}>{files.map(item => <option key={item.file}>{item.file}</option>)}</select><textarea aria-label="DDL SQL" spellCheck={false} rows={12} value={sql} onChange={event => setSQL(event.target.value)} /><div className="ddl-actions"><button type="button" className="button primary" disabled={!dirty} onClick={() => void act(async () => { if (!file) return; await window.studio.ddl.writeFile(draft.id, file.file, sql, file.hash); await readFiles(draft.id); setPreview(undefined); setMessage('DDL сохранён; прежняя версия в резервной копии.'); })}>Сохранить SQL</button><button type="button" className="button secondary" disabled={!dirty} onClick={() => { setSQL(file?.sql ?? ''); setError(''); }}>Отменить правки</button><button type="button" className="button secondary" disabled={!file || dirty} onClick={() => onOpen(draft, sql, selected)}>Открыть SQL в консоли</button></div></section>}
        <button type="button" className="button secondary" disabled={dirty} onClick={() => void act(async () => { await window.studio.ddl.remove(draft.id); setMappings(await window.studio.ddl.list()); setDraft(undefined); reset(); setMessage('Mapping удалён. SQL-файлы сохранены.'); })}>Удалить только mapping</button>
      </>}
    </fieldset>{busy && <p role="status">Выполняется…</p>}{error && <p role="alert" className="form-message error">{error}</p>}{message && <p role="status" className="form-message success">{message}</p>}</div>
  </dialog>;
}
