import { useState } from 'react';
import type { ProfileDraft } from './shared';
import type { SessionTemplate } from './jdbc';
import { DriverSelection } from './DriverCenter';

export function SessionTemplates({ draft, onChange }: { draft: ProfileDraft; onChange(draft: ProfileDraft): void }) {
  const templates = draft.jdbc?.sessionTemplates ?? [];
  const [selected, select] = useState(templates[0]?.id ?? '');
  const current = templates.find(item => item.id === selected);
  const settings = draft.jdbc ?? {};
  const update = (patch: Partial<SessionTemplate>) => onChange({ ...draft, jdbc: { ...settings, sessionTemplates: templates.map(item => item.id === selected ? { ...item, ...patch } : item) } });
  const option = (patch: NonNullable<SessionTemplate['options']>) => update({ options: { ...current?.options, ...patch } });
  return <div className="jdbc-options">
    <h3>Session templates</h3>
    <p className="muted">Шаблоны принадлежат этому подключению. Заданные поля заменяют General / Options; остальные наследуются. Изменения действуют при следующем подключении.</p>
    <div className="form-row"><label>Шаблон<select aria-label="Редактируемый шаблон" value={selected} onChange={event => select(event.target.value)}><option value="">Выберите шаблон</option>{templates.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="button" className="button secondary" disabled={templates.length >= 32} onClick={() => { const id = crypto.randomUUID(); let number = templates.length + 1; while (templates.some(item => item.name === `Session ${number}`)) number++; onChange({ ...draft, jdbc: { ...settings, sessionTemplates: [...templates, { id, name: `Session ${number}` }] } }); select(id); }}>Добавить шаблон</button></div>
    <div className="form-row">{(['defaultSessionTemplate', 'introspectionSessionTemplate'] as const).map(key => <label key={key}>{key === 'defaultSessionTemplate' ? 'Шаблон новых SQL-сессий' : 'Шаблон интроспекции'}<select aria-label={key} value={settings[key] ?? ''} onChange={event => onChange({ ...draft, jdbc: { ...settings, [key]: event.target.value } })}><option value="">Настройки подключения</option>{templates.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>)}</div>
    {current && <fieldset>
      <label>Имя шаблона<input aria-label="Имя шаблона" value={current.name} maxLength={100} onChange={event => update({ name: event.target.value })} /></label>
      <label>Authentication<select aria-label="Аутентификация шаблона" value={current.authentication?.auth ?? 'inherit'} onChange={event => update({ authentication: event.target.value === 'inherit' ? undefined : { user: draft.user, auth: event.target.value as 'none' | 'basic' | 'bearer', secret: '' } })}><option value="inherit">Наследовать</option><option value="none">Без пароля</option><option value="basic">Username / password</option>{['trino','jdbc'].includes(draft.engine) && <option value="bearer">Bearer token</option>}</select></label>
      {current.authentication && <><label>User<input aria-label="Пользователь шаблона" value={current.authentication.user} onChange={event => update({ authentication: { ...current.authentication!, user: event.target.value, secret: '', hasSecret: false } })} /></label>{current.authentication.auth !== 'none' && <label>Password / token<input type="password" autoComplete="new-password" aria-label="Секрет шаблона" value={current.authentication.secret ?? ''} placeholder={current.authentication.hasSecret ? 'Сохранён · оставьте без изменений' : ''} onChange={event => update({ authentication: { ...current.authentication!, secret: event.target.value } })} /><button type="button" className="button secondary" onClick={() => update({ authentication: { ...current.authentication!, secret: '', hasSecret: false } })}>Очистить секрет</button></label>}</>}
      <div className="form-row">{(['readOnly','autoCommit'] as const).map(key => <label key={key}>{key === 'readOnly' ? 'Read-only' : 'Auto commit'}<select aria-label={`Шаблон ${key}`} value={current.options?.[key] === undefined ? '' : String(current.options[key])} onChange={event => option({ [key]: event.target.value === '' ? undefined : event.target.value === 'true' })}><option value="">Наследовать</option><option value="true">Да</option><option value="false">Нет</option></select></label>)}</div>
      <label>Startup script override<select aria-label="Startup script override" value={current.options?.startupStatements === undefined ? 'inherit' : 'replace'} onChange={event => option({ startupStatements: event.target.value === 'inherit' ? undefined : [] })}><option value="inherit">Наследовать</option><option value="replace">Заменить (пустой отключает скрипт)</option></select></label>
      {current.options?.startupStatements !== undefined && <label>SQL шаблона<textarea aria-label="SQL шаблона" rows={5} value={current.options.startupStatements.join('\n-- next statement --\n')} onChange={event => option({ startupStatements: event.target.value.trim() ? event.target.value.split('\n-- next statement --\n') : [] })} /><small>Каждый блок — одна команда; разделитель: -- next statement -- на отдельной строке.</small></label>}
      <label className="checkbox-row"><input type="checkbox" checked={current.driverVersion !== undefined} onChange={event => update({ driverVersion: event.target.checked ? '' : undefined })} />Переопределить версию JDBC-драйвера</label>
      {current.driverVersion !== undefined && <DriverSelection draft={{ ...draft, jdbc: { ...settings, driverVersion: current.driverVersion } }} onChange={value => update({ driverVersion: value.jdbc?.driverVersion ?? '' })} />}
      <label>Driver class override<input value={current.driverClass ?? ''} placeholder="Наследовать" onChange={event => update({ driverClass: event.target.value || undefined })} /></label>
      <label>JAR override · абсолютные пути<textarea rows={2} value={current.classpath?.join('\n') ?? ''} placeholder="Наследовать" onChange={event => update({ classpath: event.target.value.trim() ? event.target.value.split('\n').filter(Boolean) : undefined })} /></label>
      <button type="button" className="button secondary" onClick={() => { onChange({ ...draft, jdbc: { ...settings, sessionTemplates: templates.filter(item => item.id !== selected), defaultSessionTemplate: settings.defaultSessionTemplate === selected ? '' : settings.defaultSessionTemplate, introspectionSessionTemplate: settings.introspectionSessionTemplate === selected ? '' : settings.introspectionSessionTemplate } }); select(''); }}>Удалить шаблон</button>
    </fieldset>}
  </div>;
}
